{{- if .Values.web.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "perhaps.fullname" . }}-web
  labels:
    {{- include "perhaps.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "perhaps.fullname" . }}-web
  minReplicas: {{ .Values.web.hpa.minReplicas }}
  maxReplicas: {{ .Values.web.hpa.maxReplicas }}
  metrics:
    {{- if .Values.web.hpa.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.hpa.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.web.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.web.hpa.customMetrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.web.hpa.behavior }}
  behavior:
    {{- toYaml .Values.web.hpa.behavior | nindent 4 }}
  {{- end }}
{{- end }}
