{{- if .Values.web.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "perhaps.fullname" . }}-web
  labels:
    {{- include "perhaps.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  {{- if .Values.web.pdb.minAvailable }}
  minAvailable: {{ .Values.web.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.web.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.web.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "perhaps.web.selectorLabels" . | nindent 6 }}
{{- end }}
