{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perhaps.fullname" . }}
  labels:
    {{- include "perhaps.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.secretKeyBase }}
  SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase | quote }}
  {{- end }}
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.gocardlessSecretId }}
  GOCARDLESS_SECRET_ID: {{ .Values.secrets.gocardlessSecretId | quote }}
  {{- end }}
  {{- if .Values.secrets.gocardlessSecretKey }}
  GOCARDLESS_SECRET_KEY: {{ .Values.secrets.gocardlessSecretKey | quote }}
  {{- end }}
  {{- if .Values.secrets.openidSigningKey }}
  OPENID_SIGNING_KEY: {{ .Values.secrets.openidSigningKey | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.database.host (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perhaps.fullname" . }}-db
  labels:
    {{- include "perhaps.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | default "" | quote }}
{{- end }}
