{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "perhaps.fullname" . }}-worker
  labels:
    {{- include "perhaps.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.worker.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "perhaps.worker.selectorLabels" . | nindent 4 }}
{{- end }}
